#!/usr/bin/env perl

use strict;
use warnings;

use W3C::XMLSchema;

my $xsd=W3C::XMLSchema->new( file => shift );
print "Target namespace: " . $xsd->target_namespace . "\n";

print "\nAttribute model groups:\n";
print "-" x 20, "\n";
foreach my $attr_group ( @{ $xsd->attribute_groups } ) {
    print $attr_group->name . "\n";
#    foreach my $attr ( @{ $attr_group->attributes } ) {
#        print "\t" . $attr->name . " (" . $attr->type . ") " . ( $attr->use eq 'required' ? '*' : '-' ) . "\n";
#    }
}

print "\nModel groups:\n";
print "-" x 20, "\n";
foreach my $group ( @{ $xsd->groups } ) {
    print $group->name . "\n";
#    foreach my $attr ( @{ $attr_group->attributes } ) {
#        print "\t" . $attr->name . " (" . $attr->type . ") " . ( $attr->use eq 'required' ? '*' : '-' ) . "\n";
#    }
}

print "-" x 20, "\n";
print "Dump finished.\n";
